In [11]:

from analysis.scripts import project_functions
project_functions.load_and_process('../data/raw/drug_deaths.csv')

,ID,Date,Age,Sex,Race,Heroin,Cocaine,Fentanyl,Fentanyl_Analogue,Oxycodone,...,Hydrocodone,Benzodiazepine,Methadone,Amphetamine,Tramadol,Morphine_NotHeroin,Hydromorphone,OpiateNOS,AnyOpioid,MannerofDeath
1,13-0102,2013-03-21,48,Male,Black,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Accident
2,16-0165,2016-03-13,30,Female,White,1,1,0,0,0,...,0,0,0,0,0,0,0,0,1,Accident
3,16-0208,2016-03-31,23,Male,White,1,0,1,0,0,...,0,0,0,0,0,0,0,0,1,Accident
4,13-0052,2013-02-13,22,Male,"Asian, Other",0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Accident
5,14-0277,2014-06-29,23,Male,White,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Accident
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5100,15-0466,2015-09-08,43,Male,White,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,Accident
5101,17-0618,2017-07-22,21,Male,White,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,Accident
5102,18-0646,2018-08-14,30,Male,White,1,0,1,1,0,...,0,0,0,0,1,0,0,0,1,Accident
5103,14-0124,2014-03-16,33,Male,White,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Accident
5104,16-0637,2016-09-15,33,Male,White,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Accident

In [9]:
 load_and_process('../data/raw/drug_deaths.csv')

NameError: name 'load_and_process' is not defined